// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcs2l01EZLjuSAaMld4EvXY0dDYqihKfs',
    appId: '1:216056451668:web:c77c5eac39dd8994ab53c1',
    messagingSenderId: '216056451668',
    projectId: 'lgs-takip-8793d',
    authDomain: 'lgs-takip-8793d.firebaseapp.com',
    storageBucket: 'lgs-takip-8793d.firebasestorage.app',
    measurementId: 'G-FT1Y2Y4L5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRfxW6vx0mbF2CeeE_ZASwVPa6gwIy6_0',
    appId: '1:216056451668:android:4e12a901711ec045ab53c1',
    messagingSenderId: '216056451668',
    projectId: 'lgs-takip-8793d',
    storageBucket: 'lgs-takip-8793d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATx5WoEb51i1_ymmGViTfGR2bK_70XGeg',
    appId: '1:216056451668:ios:88e5559f33c69e0bab53c1',
    messagingSenderId: '216056451668',
    projectId: 'lgs-takip-8793d',
    storageBucket: 'lgs-takip-8793d.firebasestorage.app',
    iosBundleId: 'com.example.okulApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATx5WoEb51i1_ymmGViTfGR2bK_70XGeg',
    appId: '1:216056451668:ios:88e5559f33c69e0bab53c1',
    messagingSenderId: '216056451668',
    projectId: 'lgs-takip-8793d',
    storageBucket: 'lgs-takip-8793d.firebasestorage.app',
    iosBundleId: 'com.example.okulApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcs2l01EZLjuSAaMld4EvXY0dDYqihKfs',
    appId: '1:216056451668:web:53d983975ed50a67ab53c1',
    messagingSenderId: '216056451668',
    projectId: 'lgs-takip-8793d',
    authDomain: 'lgs-takip-8793d.firebaseapp.com',
    storageBucket: 'lgs-takip-8793d.firebasestorage.app',
    measurementId: 'G-M77HXXGFD5',
  );
}
